### ISSUE TITLE
MultiGPU Traning

### ISSUE THREAD

**Issue by N-Almarwani** [kkjawz/coref-ee#1]
I have 4 gpus and I tired to use your code for traning and I'm getting the following errors

`Caused by op 'BackupVariables/char_embeddings/BackupVariables/cond/read/Switch_BackupVariables/char_embeddings_0', defined at:
  File "worker.py", line 31, in <module>
    model = cm.CorefModel(config)
  File "coref-ee/coref_model.py", line 92, in __init__
    for var in self.trainable_variables]
  File "coref-ee/coref_model.py", line 92, in <listcomp>
    for var in self.trainable_variables]`

would you please update point me on how exactly to run the code using multi gpus as the current instruction doesn't reflect that 

Thanks

**Comment by kkjawz** [comment]
Multi GPU training doesn't work currently, because of the ExponentialMovingAverage. If you want you can remove all references to it at the cost of slightly reduced performance and training stability.
