### ISSUE TITLE
Failed to connect to lsz-gpu-01.cs.washington.edu

### ISSUE THREAD

**Issue by lujiaying** [kkjawz/coref-ee#11]
For both `setup_all.sh` or `setup_pretrained.sh`, I could not download embedding files and pre-trained model files.

Could you provide another URL for these resources?

**Comment by jkkummerfeld** [comment]
I'm having the same problem. From Issue #14 it looks like the first necessary file is now available at a different location, as described in https://github.com/kentonl/e2e-coref. The new file is https://drive.google.com/file/d/1fkifqZzdzsOEo0DXMzCFjiNXqsKG_cHi

For the second file, I've submitted a pull request with the new URL.
