### ISSUE TITLE
Extracting BERT features throws `out_of_bounds` exceptions

### ISSUE THREAD

**Issue by abdelrhmanghreeb** [kkjawz/coref-ee#4]
When I run `extract_bert_features.sh` I get many of the following out of bounds exceptions. Here are more details:
 `Data.py exception
 51 index 1126 is out of bounds for axis 0 with size 1041` exceptions while trying to access `bert_to_orig` and `orig_to_bert` maps. here is some debugging output that I generated:
```
orig_to_bert_map.shape, orig_to_bert_end_map.shape, bert_to_orig_map.shape, self.gold_starts.shape=   
(1041,) (1041,) (2192,) (266,)

```

**Comment by kkjawz** [comment]
I added requirements.txt file, please update if the issue persists with the correct library versions.
