### ISSUE TITLE
Training never starts

### ISSUE THREAD

**Issue by abdelrhmanghreeb** [kkjawz/coref-ee#6]
I am trying to run the training script provided in your published code but the training never starts and when I debug `tensorflow coref_model.py` code, I find that the variables passed to `get_predictions_and_loss()` are never initialized. Empty tensors are passed. How can this be fixed?

**Comment by CooDL** [comment]
Can you run the code from [kentonl](https://github.com/kentonl/e2e-coref)? they have similar environment.

**Comment by abdelrhmanghreeb** [comment]
Yes, I ran Kentol's code but I was not able to run this code

**Comment by CooDL** [comment]
Haha, I also cannot run this repo code though no error occurs. I think there must some files or environments are omitted by the author. just like the previous bash scripts.

**Comment by kkjawz** [comment]
I accidentally omitted a critical line from train.py while cleaning up the code. I updated the file, please update if the problem persists. Thanks!
